### PR TITLE
Added dark mode support

### PR DESCRIPTION
**Pull request by kyledold**
I moved the colors to the assets and made them invert for dark mode so it looks more like what GitHub does when it's in dark mode.

### CODE REVIEW

**Comment by AnderGoig** [comment]
Thanks @kyledold! Really like the idea of moving the colors to the Assets 👍

The only problem I see by inverting the colors is that it could be a bit confusing. In dark mode it actually looks like you made more contributions in the days that you made less, don't you think so?

**Comment by kyledold** [comment]
Hey, 
Hmmm...maybe I need to tweak the colors slightly for when its a level 4 color.

What I was trying to do was match what Github was doing in their dark vs light mode (like below).
github_darkgithub_light

Also this has recently stopped working for me, are you aware of any changes to that Github have made recently that would break this widget?

**Comment by AnderGoig** [comment]
Yeah, maybe we can try with darker colors for less contributions and brighter (but not pale) for more contributions.

> Also this has recently stopped working for me, are you aware of any changes to that Github have made recently that would break this widget?

Yes, they changed some stuff which made the HTML parsing fail, I've fixed that in `1.0.3` but it's not live yet, still pending approval.

**Comment by kyledold** [comment]
Agreed, I'll try tweaking the colors after 1.0.3 is merged :)

**Comment by kyledold** [comment]
@AnderGoig I've made some changes to the colors (for dark mode only) so hopefully it looks a bit clearer now which days there were more contributions.

Simulator Screen Shot - iPhone 12 mini - 2021-02-08 at 12 12 38Simulator Screen Shot - iPhone 12 mini - 2021-02-08 at 12 12 54

**Comment by AnderGoig** [comment]
Yeah, much better now in my opinion! Thanks for your contribution 🙂

**Pull request merged**
